import { useEffect, useState } from 'react';
import { ClipboardCheck } from 'lucide-react';
import api from '../api/axios';

const EMPTY = { changeImplementedAsApproved: 'Yes', securityValidationDone: 'No', issuesObserved: '', rollbackExecuted: 'No', postReviewDate: '', lessonsLearned: '', closureApprovedBy: '', postReviewRemark: '', pirOutcome: 'Successful', pirNotes: '' };

const CabPostImplementation = () => {
  const [records, setRecords] = useState([]);
  const [selected, setSelected] = useState(null);
  const [form, setForm] = useState(EMPTY);
  const [error, setError] = useState('');
  const load = async () => { const response = await api.get('/change-requests'); setRecords(response.data.filter((record) => record.status === 'Implemented')); };
  useEffect(() => { load(); }, []);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { setError(''); try { await api.put(`/change-requests/${selected._id}/post-implementation`, form); setSelected(null); setForm(EMPTY); await load(); } catch (err) { setError(err.response?.data?.message || 'Could not save the post-implementation review.'); } };
  const field = (key, label, type = 'text', required = false) => <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span>{type === 'textarea' ? <textarea required={required} value={form[key]} onChange={(event) => update(key, event.target.value)} rows="3" className="focus-ring w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm" /> : <input required={required} type={type} value={form[key]} onChange={(event) => update(key, event.target.value)} className="focus-ring w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm" />}</label>;
  const select = (key, label, options) => <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span><select value={form[key]} onChange={(event) => update(key, event.target.value)} className="focus-ring w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm">{options.map((option) => <option key={option}>{option}</option>)}</select></label>;
  return <div><div className="mb-6 flex items-center gap-2"><ClipboardCheck size={22} className="text-teal-600" /><div><h1 className="text-2xl font-bold text-ink-950">CAB post review</h1><p className="mt-1 text-sm text-slate-500">Review and update post-implementation details.</p></div></div>{error && <p className="mb-4 rounded-lg border border-coral-200 bg-coral-50 px-4 py-3 text-sm text-coral-600">{error}</p>}<div className="space-y-3">{records.map((record) => <div key={record._id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-soft"><div><p className="font-mono text-xs text-slate-500">{record.crNumber}</p><h2 className="mt-1 font-semibold text-ink-900">{record.description}</h2><p className="mt-1 text-sm text-slate-500">Implementation result: {record.implementationResult}</p></div><button onClick={() => { setSelected(record); setForm({ ...EMPTY, changeImplementedAsApproved: record.changeImplementedAsApproved || 'Yes', securityValidationDone: record.securityValidationDone || 'No', issuesObserved: record.issuesObserved || '', rollbackExecuted: record.rollbackExecuted || 'No', postReviewDate: record.postReviewDate?.slice(0, 10) || '', lessonsLearned: record.lessonsLearned || '', closureApprovedBy: record.closureApprovedBy || '', postReviewRemark: record.postReviewRemark || '', pirOutcome: record.pirOutcome || 'Successful', pirNotes: record.pirNotes || '' }); }} className="rounded-lg bg-ink-950 px-3 py-2 text-sm font-semibold text-white">Post review</button></div>)}{records.length === 0 && <p className="rounded-xl border border-slate-200 bg-white px-5 py-10 text-center text-sm text-slate-400">No implemented changes are waiting for review.</p>}</div>{selected && <div className="mt-4 rounded-xl border border-teal-200 bg-teal-50 p-5"><h2 className="mb-4 font-semibold text-ink-900">Post review: {selected.crNumber}</h2><div className="grid gap-4 md:grid-cols-2">{select('changeImplementedAsApproved', 'Change implemented as approved?', ['Yes', 'No'])}{select('securityValidationDone', 'Security validation done?', ['Yes', 'No'])}{field('issuesObserved', 'Issues observed', 'textarea')}{select('rollbackExecuted', 'Rollback executed?', ['Yes', 'No'])}{field('postReviewDate', 'Post review date and time', 'datetime-local')}{field('lessonsLearned', 'Lessons learned', 'textarea')}{field('closureApprovedBy', 'Closure approved by (name and role)')}{field('postReviewRemark', 'Remark', 'textarea')}{select('pirOutcome', 'Post review status', ['Successful', 'Successful with issues', 'Failed'])}{field('pirNotes', 'Post review notes', 'textarea', true)}<div className="flex gap-2 md:col-span-2"><button onClick={submit} className="rounded-lg bg-teal-600 px-4 py-2 text-sm font-semibold text-white">Save post review</button><button onClick={() => setSelected(null)} className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm">Cancel</button></div></div></div>}</div>;
};
  
export default CabPostImplementation;
