import { useEffect, useState } from 'react';
import { Building2, PlusCircle } from 'lucide-react';
import api from '../api/axios';

const Departments = () => {
  const [departments, setDepartments] = useState([]); const [managers, setManagers] = useState([]); const [form, setForm] = useState({ name: '', email: '', primaryManager: '' }); const [error, setError] = useState('');
  const load = async () => { const [departmentRes, userRes] = await Promise.all([api.get('/departments'), api.get('/users')]); setDepartments(departmentRes.data); setManagers(userRes.data.filter((user) => ['admin', 'agent'].includes(user.role) && user.isActive)); };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setError(''); try { await api.post('/departments', form); setForm({ name: '', email: '', primaryManager: '' }); load(); } catch (err) { setError(err.response?.data?.message || 'Could not create department.'); } };
  return <div><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold text-ink-950">Departments</h1><p className="mt-1 text-sm text-slate-500">Create support departments and optionally assign a primary manager.</p></div><PlusCircle className="text-teal-500" /></div><form onSubmit={submit} className="mb-6 grid grid-cols-1 gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-soft md:grid-cols-4">{error && <p className="col-span-full text-sm text-coral-500">{error}</p>}<input required placeholder="Department name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="focus-ring rounded-lg border border-slate-200 px-3 py-2 text-sm" /><input required type="email" placeholder="Department email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="focus-ring rounded-lg border border-slate-200 px-3 py-2 text-sm" /><select value={form.primaryManager} onChange={(e) => setForm({ ...form, primaryManager: e.target.value })} className="focus-ring rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Primary manager (optional)</option>{managers.map((manager) => <option key={manager._id} value={manager._id}>{manager.name}</option>)}</select><button className="focus-ring flex items-center justify-center gap-2 rounded-lg bg-ink-950 px-3 py-2 text-sm font-semibold text-white"><Building2 size={16} /> Create department</button></form><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-soft"><table className="w-full text-sm"><thead><tr className="border-b border-slate-100 bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-400"><th className="px-5 py-3">Department</th><th className="px-5 py-3">Email</th><th className="px-5 py-3">Primary manager</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{departments.map((department) => <tr key={department._id}><td className="px-5 py-3.5 font-medium text-ink-900">{department.name}</td><td className="px-5 py-3.5 text-slate-600">{department.email}</td><td className="px-5 py-3.5 text-slate-600">{department.primaryManager?.name || '—'}</td><td className="px-5 py-3.5">{department.isActive ? 'Active' : 'Inactive'}</td></tr>)}</tbody></table></div></div>;
};
export default Departments;
